// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/4/2025, 2:11:41 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/fadel/Github/collaborative_drawing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fadel/Github/collaborative_drawing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fadel/Github/collaborative_drawing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fadel/Github/collaborative_drawing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fadel/Github/collaborative_drawing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fadel/Github/collaborative_drawing/plugins/**/*.{js,ts,mjs}","/home/fadel/Github/collaborative_drawing/composables/**/*.{js,ts,mjs}","/home/fadel/Github/collaborative_drawing/utils/**/*.{js,ts,mjs}","/home/fadel/Github/collaborative_drawing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/fadel/Github/collaborative_drawing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/fadel/Github/collaborative_drawing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;